<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<p><?= $escaper->escapeHtml($block->getUrl('dvcampus_layout_debug/index/layoutresponse')) ?></p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque delectus maiores repellat! Asperiores illo iusto
    nostrum sequi! Aut commodi, cum dolorem eaque ipsa, ipsum iste quia quisquam sunt temporibus voluptates.</p>
