<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<p></p>
<html>
<head>
</head>
<body>
    <?= $escaper->escapeHtml(__('RedirectResponseDemo: ')) ?>
    <a href="<?= $escaper->escapeHtmlAttr('url_parameter_redirectresponsedemo') ?>">
        <?= $escaper->escapeHtml($block->getData('url_parameter_redirectresponsedemo')) ?>
    </a>
    <br>
    <?= $escaper->escapeHtml(__('JsonResponseDemo: ')) ?>
    <a href="<?= $escaper->escapeHtmlAttr($block->getData('url_parameter_pagejsonresponsedemo')) ?>">
        <?= $escaper->escapeHtml($block->getData('url_parameter_pagejsonresponsedemo')) ?>
    </a>
    <br>
    <?= $escaper->escapeHtml(__('ForwardResponseDemo: ')) ?>
    <a href="<?= $escaper->escapeHtmlAttr($block->getData('url_parameter_forwardresponsedemo')) ?>">
        <?= $escaper->escapeHtml($block->getData('url_parameter_forwardresponsedemo')) ?>
    </a>
    <br><br>


    <form method="get" action="pagejsonresponsedemo">
        <label><?= $escaper->escapeHtml(__('vendor name:')) ?></label><br>
        <input type="text" name="vendor" value="YaroslavN"><br><br>
        <label><?= $escaper->escapeHtml(__('module name:')) ?></label><br>
        <input type="text" name="module" value="YaroslavN_ControllerDemos"><br><br>
        <button type="submit"><?= $escaper->escapeHtml(__('Submit')) ?></button>
    </form>
</body>
</html>

